apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ecocheck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: docker.io/darkata/ecocheck-backend:latest
          imagePullPolicy: IfNotPresent
          command:
            - node
            - apps/backend/dist/src/main.js
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: backend-secret
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
