apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecocheck
  namespace: ecocheck
spec:
  ingressClassName: traefik
  rules:
    - host: app.ecocheck.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 3000
    - host: api.ecocheck.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 3000
    - host: grafana.ecocheck.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000
    - host: alerts.ecocheck.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: alertmanager
                port:
                  number: 9093
